services:
  - type: web
    name: n8n
    runtime: docker
    plan: free
    repo: https://github.com/AndyTheMaVN/render-n8n-odoo-hosting.git
    branch: main
    dockerContext: .
    region: singapore
    envVars:
      - key: N8N_BASIC_AUTH_ACTIVE
        value: "true"

  - type: web
    name: odoo
    runtime: docker
    plan: free
    repo: https://github.com/AndyTheMaVN/render-n8n-odoo-hosting.git
    branch: main
    dockerContext: .
    region: singapore
