
services:
  - type: web
    name: n8n
    runtime: docker
    plan: free
    dockerCommand: "" 
    repo: https://github.com/AndyTheManVN/render-n8n-odoo-hosting.git  
    dockerContext: .  
    image: n8nio/n8n:latest 
    region: singapore 
    numInstances: 1
    healthCheckPath: /healthz
    envVars:
      - key: N8N_BASIC_AUTH_ACTIVE
        value: true
      - key: N8N_BASIC_AUTH_USER
        value: admin
      - key: N8N_BASIC_AUTH_PASSWORD
        sync: false  
      - key: N8N_HOST
        fromService:
          type: web
          name: n8n
          property: host  
      - key: N8N_PORT
        value: 5678
      - key: N8N_PROTOCOL
        value: https
      - key: DB_TYPE
        value: postgresdb
      - key: DB_POSTGRESDB_HOST
        value: SUPABASE_N8N_HOST  
      - key: DB_POSTGRESDB_PORT
        value: 5432
      - key: DB_POSTGRESDB_DATABASE
        value: postgres  
      - key: DB_POSTGRESDB_USER
        value: postgres
      - key: DB_POSTGRESDB_PASSWORD
        sync: false  
      - key: WEBHOOK_URL
        value: https://YOUR_N8N_DOMAIN.onrender.com/  
        value: Asia/Bangkok

  - type: web
    name: odoo
    runtime: docker
    plan: free
    dockerCommand: ""
    repo: https://github.com/AndyTheManVN/render-n8n-odoo-hosting.git
    branch: main
    dockerContext: .
    image: odoo:17.0  
    region: singapore
    numInstances: 1
    healthCheckPath: /web/health
    envVars:
      - key: HOST
        value: SUPABASE_ODOO_HOST  
      - key: PORT
        value: 5432
      - key: USER
        value: postgres
      - key: PASSWORD
        sync: false  
      - key: DB_NAME
        value: postgres  
